name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  flutter_bloc: ^9.1.1
  get: ^4.7.2
  go_router: ^16.3.0
  equatable: ^2.0.7
  permission_handler: ^12.0.1
  audio_waveforms: ^1.3.0
  record: ^6.1.2
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  dartz: ^0.10.1
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  path: ^1.9.1
  get_it: ^8.2.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
